[package]
name = "space-shooter"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[dependencies]
bevy = "0.8.1"
bevy-inspector-egui = "0.13.0"
rand = "0.8.5"

